name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: CI Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - 3.8
        toxenv: [ csslint,eslint,pycodestyle,pylint,django22,django30,django31,django32 ]
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install pip
      run: |
      pip install -r requirements/pip.txt
      export BOTO_CONFIG=/dev/null

    - name: Install requirements
      run: make requirements_ci

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Run Coverage
      if: matrix.python-version == '3.8' && matrix.toxenv=='django32'
      uses: codecov/codecov-action@v1
