name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
        - '3.11'
        - '3.12'
        toxenv: [django42, django52, quality, csslint, eslint, translations_validate]

    steps:
    - uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Set BOTO_CONFIG value
      run: export BOTO_CONFIG=/dev/null

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: make requirements_ci

    - name: Install GNU gettext
      run: sudo apt-get install gettext

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: |
        tox
